### ISSUE TITLE
Дэн не дал рецепт.

### ISSUE THREAD

**Issue by ghost** [dsh2dsh/op2ogse#10]
Дэн на болотах выдал квест на пиво из лаборатории в ТД. После сдачи квеста сказал, что дал какой-то рецепт. 

Никаких новых рецептов не добавилось.

Если от меня что-то нужно, пожалуйста,  дайте знать.

**Comment by dsh2dsh** [comment]
Вспомни диалог с ним при взятии задания. Или загрузи сейв и прочитай. Он там даже имя упоминает того, от кого ты этот рецепт уже получил. Вот этот рецепт он и дал. Только для тебя он не новый.

**Comment by ghost** [comment]
Спасибо за столь быстрый ответ.
