### ISSUE TITLE
Пара вылетов, подвисание нпс и вопрос.

### ISSUE THREAD

**Issue by Kokokokoka** [dsh2dsh/op2ogse#13]
В целом, играется очень хорошо, но есть пара моментов:

- Если игрок забыл вырубить телепорт под агропромом и ты не можешь вернуться в тайник, повторно скрипт с телепортами не работает.

- Вылет в лабе х18, если долго стоять у закрытой двери (после второго удара), происходит вылет, смог обойти, успев ввести код, до второго удара

- Янтарь, Сахаров несколько раз зависал после х10 иили при квесте на измерения, приходилось переигрывать (при этом у него странно выгибались руки и отсутствовала возможность поговорить), была гипотеза, что это из-за монстров, зачистил всю территорию перед походом в лабу и вроде это помогло.

- Псевдособаки порой спавнятся в безумных количествах, превращая в лагодром игру, может ограничить им макс деление?

- вылет на болотах при поднятии рюкзака, который взрывается (по квесту для Василия (пока что не нашёл как обойти, пробовал сбрасывать свой рюкзак рядом -- не помогло), в одном из тайников нашёл две баночки, думал, что найду ещё)

- После отключения выжигателя в х10 -- вылет, после выхода из лабы, когда идёт аудио от военных (пробовал подождать завершения и отпустить паузу -- разницы нет (даже откатился до похода в х10 и прошёл пару кветов, но ничего не изменилось -- стабильный вылет)) 
лог: https://dpaste.org/O2vd
[29.11.20 22:16:33.324] [OGSR Engine (x64)] build date: [Nov 17 2020 12:09:36]
Если правильно помню, то сборка: fdcf78e5b9245aacb8af91c8744e75dd4fa94a05
Ставил основную часть, последнее обновление. запускаю в вайне 64

**Comment by dsh2dsh** [comment]
Поддерживается только запуск под win 10.

**Comment by Kokokokoka** [comment]
При случае попробую воспроизвести в 10, если у меня будет возможность. Сам факт, что игра работает стабильно (большую часть времени) говорит о том, что хорошо бы понять, в чём дело и, с большой вероятностью это не проблема вайна. я бы сам отладил, но понадеялся на (хотя бы) совет разработчика -- зря.
+ тут есть то, что однозначно имеет место и в винде (телепорт и собаки)

**Comment by Kokokokoka** [comment]
@dsh2dsh спасибо огромное за фиксы, теперь места скриптовые, что тут были упомянуты, работают хорошо.
только есть одно но, когда появляется чувак по квесту на болотах, если рядом будут монстры, то скрипту поплохеет. если надо, могу скинуть лог.
и ещё вопрос, я собираю из последней студии 2019. делаю так: релиз, билд солюшн. но, потом игра говорит что нет fsgame.ltx или fs.ltx, но твой бинарник использует другой файл. Похоже мне надо было прагму ванс найти и там поправить погоду и прочее, это достаточное условие?
