### ISSUE TITLE
Невозможно начать игру на мастере! 

### ISSUE THREAD

**Issue by MoonlightRay** [dsh2dsh/op2ogse#2]
Как-то совсем туго начинается игра на мастере... 

Обычно это происходит по 2м сценариям:

https://youtu.be/zy1nzr2It64
https://youtu.be/labOUWMqyrg

Имхо, но спавн на мастере в том месте кордона какой-то чрезвычайно лютый

**Comment by dsh2dsh** [comment]
Это не спаун. Они там изначально живут. Вот так оно бывает:

https://www.youtube.com/watch?v=JTf6vSGwLn0

Иногда история Меченого заканчивает быстро, но он всегда возвращается в начало. Это и дар и проклятье.

**Comment by MoonlightRay** [comment]
Ладно, едем дальше :D 

Сцена вторая: 

https://youtu.be/7pQbwmGHI6E

То ли мне показалось, толи нпс сагрились на собак которые находются чуть ли не на болотах.

**Comment by dsh2dsh** [comment]
Бывает. Зона все-таки. Помоги сталкерам зачистить собачек, они и успокоятся.
