### ISSUE TITLE
Днём - темно, ночью - светло

### ISSUE THREAD

**Issue by MoonlightRay** [dsh2dsh/op2ogse#3]
Впервые вижу подобный баг неимоверной странности, но по игровому времени получается что днём - темно, ночью - светло

https://youtu.be/F0KAOawKRjY

Как-то можно исправить?

**Comment by dsh2dsh** [comment]
Исправить очень просто. Нужно дождаться, когда закончится ливень и прояснится.

**Comment by MoonlightRay** [comment]
Он не заканчивается уже вторые сутки, это нормально?

**Comment by dsh2dsh** [comment]
Нет каких-либо ограничений. Как рандом выпадет, такая погода и будет.
