### ISSUE TITLE
Дубликат

### ISSUE THREAD

**Issue by ISTORMI** [dsh2dsh/op2ogse#36]
https://github.com/dsh2dsh/op2ogse/blob/49a792a3a242214bbfd8eb72af3faf193ef86086/gamedata/config/text/rus/sms_arhara_dialog.xml#L1438 https://github.com/dsh2dsh/op2ogse/blob/49a792a3a242214bbfd8eb72af3faf193ef86086/gamedata/scripts/arhara/arhara_dialog.script#L7454 Смску заменить т.к.
https://github.com/dsh2dsh/op2ogse/blob/49a792a3a242214bbfd8eb72af3faf193ef86086/gamedata/config/text/rus/string_table_level_tips.xml#L114

**Comment by dsh2dsh** [comment]
Исправлено в https://github.com/dsh2dsh/op2ogse/commit/4b6f2c40c7b318f7009f65526fce8af43819e2b6
