### ISSUE TITLE
Костя и его подсказки

### ISSUE THREAD

**Issue by ISTORMI** [dsh2dsh/op2ogse#37]
https://github.com/dsh2dsh/op2ogse/blob/4b6f2c40c7b318f7009f65526fce8af43819e2b6/gamedata/scripts/taynik_spawn.script#L794
https://github.com/dsh2dsh/op2ogse/blob/4b6f2c40c7b318f7009f65526fce8af43819e2b6/gamedata/config/text/rus/stashes_kostya.xml#L16 `<text>Здесь, на Кордоне</text>` и подобное, в начале его подсказок, возвращать нет желания ? Если нет, тогда просто поправить в таких местах заглавную букву? Если не ошибаюсь в 100% случаев с маленькой буквы все они.
![image](https://user-images.githubusercontent.com/75955587/208311553-6dfaa3b1-d287-447d-8ac1-6fa175fc6e84.png)

**Comment by dsh2dsh** [comment]
Все правильно, с маленькой и должно быть. Ведь это продолжение фразы в "Получено задание:".

**Comment by ISTORMI** [comment]
Тогда и цвет этого текста должен быть сейм, а не разный, иначе это никак не продолжение. Это просто новое предл. с маленькой буквы.
