### ISSUE TITLE
Мусор в КПК

### ISSUE THREAD

**Issue by ISTORMI** [dsh2dsh/op2ogse#41]
https://github.com/dsh2dsh/op2ogse/blob/eb397de44a87fb548c28d449239b0ec5a26197b0/gamedata/config/text/rus/stable_storyline_info_radar.xml#L4 Запись в КПК, падает с рандомного монолитовца, при первом заходе на Радар. Из оригинала, там это - код к двери в x-10, за которой разный лут. А у нас там тайник Кости, и код офк - другой.
КПК и так перегружен мусором...

**Comment by dsh2dsh** [comment]
В этом нет необходимости, пусть остается.
