### ISSUE TITLE
dsh_rukzak.script

### ISSUE THREAD

**Issue by ISTORMI** [dsh2dsh/op2ogse#44]
https://github.com/dsh2dsh/op2ogse/blob/ab8edf61e37336b5e742f90f9827c5dbaf521d84/gamedata/scripts/dsh/dsh_rukzak.script#L1749
https://github.com/dsh2dsh/op2ogse/blob/ab8edf61e37336b5e742f90f9827c5dbaf521d84/gamedata/config/ui/ui_dsh_rukzak_16.xml#L47
Для рюкзака делать отдельный хмл или куда-то закинуть текст в готовый ? Там около 35-40 строк

**Comment by ISTORMI** [comment]
https://github.com/dsh2dsh/op2ogse/blob/ab8edf61e37336b5e742f90f9827c5dbaf521d84/gamedata/scripts/dsh/dsh_rukzak.script#L1720 `<text>%c[default]Текущая метка:\n• </text>`
упд, вот это что такое, или оно не юзается?

**Comment by dsh2dsh** [comment]
> Для рюкзака делать отдельный хмл или куда-то закинуть текст в готовый ?

Думаю в `string_table_ui.xml` самое то.

> упд, вот это что такое, или оно не юзается?

В рюкзак можно полодить маячок и написать к нему свой текст.
