### ISSUE TITLE
Монстры не обладают своими способностями

### ISSUE THREAD

**Issue by ZloyPotroh** [dsh2dsh/op2ogse#5]
Странный баг, Денис. Сделал сейв в подземке, на винтовой лестнице со стороны базы вояк тусуют сосатели. И проблема в том, что они не пинаются дистанционным пси-пинком (нигде). И вообще с монстрами беда, с самого начала игры. Собаки не выносят пушку с рук, кабаны без радиации, псевдопсы тоже только кусают.

Сначала я думал, может так и надо, но, судя по всему, это проблема. Не уверен, достаточно ли будет только сейва, если что потребуется еще, предоставлю.

[save.zip](https://github.com/dsh2dsh/op2ogse/files/1790423/save.zip)

**Comment by dsh2dsh** [comment]
Спасибо, гляну подробнее. А то я сейчас даже и сам уже не уверен.

**Comment by dsh2dsh** [comment]
https://github.com/dsh2dsh/op2ogse/commit/ab9d98c86df28176fa744f87e684f4f5d584bfe7
