### ISSUE TITLE
Флешка Круглова

### ISSUE THREAD

**Issue by ISTORMI** [dsh2dsh/op2ogse#50]
У Круглова его флешка `bar_ecolog_flash` в продаже есть, можно выкупить недорого. Потом он даст еще и вторую. По итогу, тыкая в диалог сдачи флешки - Бармену, на 3й раз будет вылет по `out_items_number`,`out_item_namber`.

**Comment by dsh2dsh** [comment]
Поправил.

**Comment by ISTORMI** [comment]
> Поправил.
Вылет по `out_items_number` , `out_item_namber` - остался, если тыкнуть диалог после сдачи флешки, который не пропадает.
Диалог - `bar_bar_barman_ecolog_flash_done_0`
![image](https://user-images.githubusercontent.com/75955587/224375377-35af576d-5b45-44d8-ae59-9c1e2a729aa6.png)

**Comment by dsh2dsh** [comment]
Еще поправил.
