### ISSUE TITLE
Бинокли у нпц и супергаусс патроны к нему.

### ISSUE THREAD

**Issue by ISTORMI** [dsh2dsh/op2ogse#51]
https://github.com/dsh2dsh/op2ogse/blob/849fe93049238b1a57bb76773455093b97e5f3c9/gamedata/config/weapons/weapons.ltx#L1315 ;не править! Это для бинокля!
и далее [ammo_super_gauss1]
https://github.com/dsh2dsh/op2ogse/blob/849fe93049238b1a57bb76773455093b97e5f3c9/gamedata/config/weapons/w_binoc.ltx#L49
https://github.com/dsh2dsh/op2ogse/blob/849fe93049238b1a57bb76773455093b97e5f3c9/mods/hard_binoc/config/weapons/w_binoc.ltx#L50
![image](https://user-images.githubusercontent.com/75955587/214057689-90ad1090-9c4e-4aaf-b877-f93f7a089577.png)
Уже говорил про отряд Черепа на АС, где у каждого бинокль и пачка супер-гаусса в трупе. Тут и другие нпс, типа Петрухи, как на скрине.

**Comment by dsh2dsh** [comment]
Пусть остается, не важно это.
