### ISSUE TITLE
Очепятка

### ISSUE THREAD

**Issue by ISTORMI** [dsh2dsh/op2ogse#52]
https://github.com/dsh2dsh/op2ogse/blob/849fe93049238b1a57bb76773455093b97e5f3c9/gamedata/config/text/rus/string_table_enc_mutants.xml#L276 https://github.com/dsh2dsh/op2ogse/blob/849fe93049238b1a57bb76773455093b97e5f3c9/gamedata/config/gameplay/encyclopedia_mutants.xml#L349
Изменить где-то заглавную букву, а то в кпк:
![image](https://user-images.githubusercontent.com/75955587/214106271-e07b856a-80eb-413c-95c5-e58d114b12f1.png)

**Comment by dsh2dsh** [comment]
Поправил.
