### ISSUE TITLE
Перенос текста.

### ISSUE THREAD

**Issue by ISTORMI** [dsh2dsh/op2ogse#54]
https://github.com/dsh2dsh/op2ogse/blob/1f0e72545ca33908c822326cc8c8f066147a70cd/gamedata/config/text/rus/stable_dialogs_snp.xml#L4111 И далее, это диалог Осведомителя в баре, про покупку карты Пещеры за 20к. Файл мусорный, примерно на 99%. Не против если эти диалоги перекину в другое место, например на своё, в `stable_dialogs_bar.xml` ? Тут уже необходимость, трогать огромные мусорные хмл из-за нескольких строк для транслита - идея очень плохая.

**Comment by dsh2dsh** [comment]
Я перенес это в `stable_dialogs_bar.xml`
