### ISSUE TITLE
Арты в тайниках.

### ISSUE THREAD

**Issue by ISTORMI** [dsh2dsh/op2ogse#56]
https://www.amk-team.ru/forum/topic/13176-dsh-mod/?do=findComment&comment=1447832
Нет желания выдачу тайников посмотреть? Переигровки - меняют искусственные арты на натуральные, и наоборот. Тут и с трупов, и за 40 кпк, и за водку, м.б. еще какие-то.

**Comment by dsh2dsh** [comment]
Поправил.
