### ISSUE TITLE
Ошибка в тексте

### ISSUE THREAD

**Issue by ISTORMI** [dsh2dsh/op2ogse#69]
https://github.com/dsh2dsh/op2ogse/blob/a81b86f9ef3b9dd213220f16e568921001f5f22c/gamedata/config/text/rus/sms_battle.xml#L112 От скриптов осталось `".."`
Если еще какие то косяки переноса текста найду, делать запросы или сразу фиксить ?

**Comment by dsh2dsh** [comment]
Да, сразу исправляй.
