### ISSUE TITLE
Вылет при использовании лекарства болотного доктора при первом посещении пещеры.

### ISSUE THREAD

**Issue by ghost** [dsh2dsh/op2ogse#7]
Что было до этого:
- установил игру по инструкции
- установил текстурный пак 1 и 2. Удалил в папке mods файлы, указанные в интсрукции
- установли настройки управления и начал играть

Скриншот вылета - https://yadi.sk/i/1v32vdfX3a6ghN
Папка userdata - https://yadi.sk/d/KA9am0sv3a6gjd

Буду признателен за решение.

**Comment by dsh2dsh** [comment]
Ночью дам ссылку на исправление

**Comment by ghost** [comment]
Спасибо.

**Comment by dsh2dsh** [comment]
Вот тут исправление: [https://drive.google.com/open?id=1RnGD8OYlEcDumWQbXAhojyHImg16XsJW](url)

**Comment by ghost** [comment]
Всё рбаотает. Еще раз спасибо.
