### ISSUE TITLE
Кринжовая Муха, Пантера...

### ISSUE THREAD

**Issue by ISTORMI** [dsh2dsh/op2ogse#75]
Тут без доп. комментариев...
Муха (моделька мужика с головой непонятно от чего)
![ss_storm_03-18-23_14-41-56_(aver)](https://user-images.githubusercontent.com/75955587/226126592-16f99323-444b-442e-aa60-98b05b1899df.png)
Или например вот так:
![ss_storm_03-18-23_14-21-38_(aver)](https://user-images.githubusercontent.com/75955587/226126629-c27d86b2-4f4a-4d07-8f32-cdc0934a6647.png)
Или или (мне не очень нра. и есть косяки с моделькой)
![ss_storm_03-18-23_14-33-38_(aver)](https://user-images.githubusercontent.com/75955587/226126722-aaca1444-10b2-45e1-8620-16581a8e4706.png)
Пантера (какой-то перс из HL без комментариев)
![ss_storm_03-18-23_18-24-42_(marsh)](https://user-images.githubusercontent.com/75955587/226129210-ba64c794-1bb0-4325-841b-951a9d9ffaae.png)
Или например вот так:
![ss_storm_03-18-23_18-26-59_(marsh)](https://user-images.githubusercontent.com/75955587/226129567-f1e0fefb-929f-4fda-968f-de99a5ae2b0c.png)
Или или (тут нужно с текстурами работать и волосы странные, мне не нрав. )
![ss_storm_03-18-23_20-04-56_(marsh)](https://user-images.githubusercontent.com/75955587/226129657-18612d00-efd1-48b7-9bb1-23ab657256b4.png)
Видео не делал, скринов по идее хватит.

**Comment by dsh2dsh** [comment]
Ну-у-у... На мой вкус все замены Пантеры еще хуже, чем имеющаяся. На замену Мухе последний вариант еще куда не шло. Элли в тащить не нужно. Вообще ну нужно тащить персонажей из других игр.

**Comment by ISTORMI** [comment]
Пантера и та и другая сделана с разраба оп2. Та которая в камуфляже из оп2.2. Всё что на скринах , кроме Пантеры-наёмника (что более чем в тему) из оп2.2. Я ничего не навязываю, как обычно. Персонаж Пантера из ХЛ - деревянный и топорный, к которому ноль эмпатии, учитиывая диалоги.

**Comment by dsh2dsh** [comment]
Все эти персонажи из других игровых вселенных. Не нужно тащить мобов их других игровых вселенных, типичный miscast получается. А ОП2 в пример вообще не нужно приводить, т.к. это ярчайший пример "васянки", куда тащат все, что плохо лежит, не смотря на то, подходит оно для этого игрового мира или нет.

**Comment by ISTORMI** [comment]
Пример оп не просто так именно сейчас и в этом месте, `это другое` Муха-мужик с квадратным лицом из 1.5 полигона- это кринж , Пантера - из ХЛ аналогично, смысла спорить нет. Это не разговор про кучи топорных мобов или куча оружия ради оружия, мусор этот убрали ? А неписей? Вот тото и оно. 
Как я понял уже и Муха не нужна? То там косяки с лицом, с очками в основном. Фиксить только если будет меняться старая моделька.

**Comment by ISTORMI** [comment]
> Как я понял уже и Муха не нужна? То там косяки с лицом, с очками в основном. Фиксить только если будет меняться старая моделька.

В модельки были прописаны кривые шейдеры, потому и косяки, каждый раз удивляешься ОП и тем, что там внутри, как такое упустить можно в работе - загадка.
![ss_storm_03-19-23_18-15-35_(aver)](https://user-images.githubusercontent.com/75955587/226189422-ee520ba4-480d-4a75-adff-814816f5627c.png)

**Comment by dsh2dsh** [comment]
Эта выглядит подходяще, вот только голова у ней какая-то слишком большая. Да и руки, как у гиббона, что тоже выглядит странно.

**Comment by ISTORMI** [comment]
Это из-за FOV'а , вот видос - https://drive.google.com/file/d/1bGTy3OnlVJVpnCrA-cVrEhpAtglRG7DL/view?usp=sharing заодно и Пантеру, волосы пофиксил - стало другое дело. Визуал наймов конечно лучше т.к. перс по сюжету типа найм, но косяки обнаружились с глазами, да и моделька ЗП, нужно анимации добавлять или переделывать.

**Comment by ISTORMI** [comment]
Наверно сюда же и напишу, про анимацию у нпс с КПК, у них же в руках кривая лопата а не КПК ? Тут, пожалуй очень в тему будет, про большая голова и прочее. 
![image](https://user-images.githubusercontent.com/75955587/226410145-03de704a-b331-4147-9b9c-0fe9a98e4d0a.png)
Должно быть примерно вот так -
![image](https://user-images.githubusercontent.com/75955587/226412556-790f9d84-7c5a-47c8-9e68-6b13aa3de6be.png)
видео, если что- https://drive.google.com/drive/folders/1PA2bZaG7Ndf-teeDRdbgEhdkki6uECAM?usp=sharing

**Comment by dsh2dsh** [comment]
Не, обе мне не нравятся. Имеющиеся тоже не ахти, но они хотя бы привычные. А новые не вписываются визуально вообще.
