### ISSUE TITLE
кв встреча с чд

### ISSUE THREAD

**Issue by ISTORMI** [dsh2dsh/op2ogse#77]
Какие то странные варианты ответов в диалогах с ЧД, а в одних из просто вылет т.к. гг типа отдает `af_part_monolit2` который еще никто не варил. Сюда же в начало м.б. еще проверку на арты, бо все диалоги листает без артефактов в рюкзаке, при этом гг в диалогах говорит что арты у него есть. 
сейв [storm_quicksave_2.zip](https://github.com/dsh2dsh/op2ogse/files/11361269/storm_quicksave_2.zip)

**Comment by dsh2dsh** [comment]
Спасибо, поправил.
