### ISSUE TITLE
Кузнецов не берет ликёр Бейлиз

### ISSUE THREAD

**Issue by ghost** [dsh2dsh/op2ogse#8]
Последовтаельность дейтсвий:
1. Взял квест у Кузнецова.
2. пошёл сразу в бар к Бармену.
3. Нашёл ликёр в штабе долга.
4. Отнёс Кузнецову. Диалога сдачи квеста не было.
5. Выложил ликёр в тайник, полсе опять положил в инвентарь. И попробовал ещё раз. Не помогло.
6. Пошёл к Сидоровичу. У него остался диалог, мол нет у него ликёра.
7. Вернулся к Кузнецову и опять попробовал сдать квест. Соотвествующего диалога снова не было.

Буду благорарен за решение. Если от меня что-то нужно, дайте знать.

И ещё, пожалуйста, напишите в двух словах чем отличаются изоморфные патроны от обычных?

**Comment by dsh2dsh** [comment]
Кузнецову нужен не один Бейлиз, а все.

Про патроны можно самостоятельно сделать вывод, в игре.

**Comment by ghost** [comment]
Я нашёл две бутылки. Кузнецову нужно больше?

**Comment by dsh2dsh** [comment]
Кузнецову нужны все.
