### ISSUE TITLE
Вылет при защите барьера.

### ISSUE THREAD

**Issue by ghost** [dsh2dsh/op2ogse#9]
1. Первый раз зашёл на АС.
2. Взял квест на защиту барьера, чтобы получтиь огнемет.
3. При убийтсве монолитовцев - вылет. Мне кажется при убийстве конкретного монолитовца вылетает.

Буду признателен за вашу помощь. Скрины ошибок и лог:

![1](https://user-images.githubusercontent.com/32170181/45515127-f1483080-b7af-11e8-9daa-5b43cc29af4a.jpg)

![2](https://user-images.githubusercontent.com/32170181/45515136-f7d6a800-b7af-11e8-9e65-96a425dbda60.jpg)

[xray_user.log](https://github.com/dsh2dsh/op2ogse/files/2380932/xray_user.log)

**Comment by dsh2dsh** [comment]
Исправление вот тут: https://drive.google.com/open?id=1RnGD8OYlEcDumWQbXAhojyHImg16XsJW
Ставить только на последнее обновление.

**Comment by ghost** [comment]
Спасибо вам. Вылет исчез.
